version: '3.8'

services:
  app:
    image: sayilxonovfikrat/nestjs-app:latest 
    restart: always 
    env_file:
      - .env 
    ports:
      - "4001:3000" 
    volumes:
      - ./data/uploads:/app/uploads 